#cloud-config
package_upgrade: true
packages:
  - nginx
  - nodejs
  - npm
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80;
        location / {
          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection keep-alive;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }
  - owner: azureuser:azureuser
    path: /home/azureuser/myapp/index.js
    content: |
      var express = require('express')
      var app = express()
      var os = require('os');
      app.get('/', function (req, res) {
        res.send('Hello World from host ' + os.hostname() + '!')
      })
      app.listen(3000, function () {
        console.log('Hello world app listening on port 3000!')
      })
  - path: /etc/systemd/system/myapp.service
    content: |
      [Unit]
      Description=My Node.js App
      After=network.target
 
      [Service]
      ExecStart=/usr/bin/nodejs /home/azureuser/myapp/index.js
      Restart=always
      User=azureuser
      Group=azureuser
      Environment=PATH=/usr/bin:/usr/local/bin
      Environment=NODE_ENV=production
      WorkingDirectory=/home/azureuser/myapp
 
      [Install]
      WantedBy=multi-user.target
runcmd:
  - systemctl restart nginx
  - systemctl enable myapp
  - systemctl restart myapp
